# Generated by Django 4.2.23 on 2025-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_options_alter_monster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
