# Generated by Django 4.2.23 on 2025-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_observation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='etymology',
            field=models.CharField(default='blank', max_length=500),
            preserve_default=False,
        ),
    ]
