# Generated by Django 4.2.23 on 2025-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_monster_etymology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='category',
            field=models.CharField(choices=[('Chaos', 'Chaos'), ('Holy', 'Holy'), ('Marine', 'Marine'), ('Nature', 'Nature'), ('Aeries', 'Aeries'), ('Pyro', 'Pyro'), ('Twilight', 'Twilight')], max_length=50),
        ),
    ]
