# Generated by Django 4.2.23 on 2025-08-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_observation_expanded_danger_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='danger_rating',
            field=models.IntegerField(choices=[(1, '1 - Harmless'), (2, '2 - Low Risk'), (3, '3 - Moderate'), (4, '4 - High Risk'), (5, '5 - Extremely Dangerous')]),
        ),
    ]
