# Generated by Django 4.2.23 on 2025-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_observation_danger_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='expanded_danger_rating',
            field=models.TextField(),
        ),
    ]
