# Generated by Django 4.2.23 on 2025-08-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_observation_expanded_danger_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.monster'),
        ),
    ]
