# Generated by Django 4.2.23 on 2025-08-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_comment_monster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.observation'),
        ),
    ]
