# Generated by Django 4.2.23 on 2025-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_comment_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
